version: '3.9' # version of the code below


services:
  # list of services
  app:
    # name of service
    build:
      context: . # build the docker file inside the current directory
      args:
        - DEV=true
    ports:
      - "8181:8181" # maps the port of current machine to the port of container
    volumes:
      - ./app:/app # this helps to reflect any changes in code to container (wirthout re-building)
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8181"
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data-ticket:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  dev-db-data-ticket:
