---
name: Checks

on: [push] # make it run on push

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    env: # Define environment variables here
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
    steps:
      - name: Loging to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db &&
                                                python manage.py migrate &&
                                                python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"